[build-system]
requires = ["setuptools>=68", "wheel"]
build_backend = "setuptools.build_meta"

[project]
name = "stochastic-control"
version = "0.1.0"
description = "control everything"
requires-python = ">=3.12.1"
readme = "README.md"
dependencies = ["numpy>=2.5.1", "scipy>=1.18.0", "sympy>=1.14.0", "cvxpy>=1.9.2"]

[tool.setuptools.packages.find]
where = ["src"]
